# FROM openjdk:17-jdk-alpine
FROM eclipse-temurin:17-jdk-alpine
VOLUME /tmp 

## when define `ARG` like this, you need to provide corresponding `ARG` when build the image (e.g. --build-arg JAR_FILE=?)
ARG JAR_FILE
ARG DB_SOURCE_PW
ARG DB_SOURCE_URL
ARG DB_SOURCE_USERNAME

ENV SPRING_DATASOURCE_PASSWORD=${DB_SOURCE_PW}
ENV SPRING_DATASOURCE_URL=${DB_SOURCE_URL}
ENV SPRING_DATASOURCE_USERNAME=${DB_SOURCE_USERNAME}

# ENV SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
# ENV SPRING_DATASOURCE_USERNAME=sa
# ENV SPRING_DATASOURCE_PASSWORD=

COPY ${JAR_FILE} /tdd-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","/tdd-0.0.1-SNAPSHOT.jar"]
